spring:
 application:
  name: thinkpro-bank

# Database  
 datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/thinkprobankdb
  username: root
  password: satheesh  jpa:    hibernate:      ddl-auto: validate    properties:      dialect: org.hibernate.dialect.MySQL5Dialect  
server:
 port: 9090

eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8761/eureka
   preferIpAddress: true








